#!/usr/bin/env bash
# User-level installer for the Spitch voice-input daemon (v0.2).
#
# What it does (no sudo for the package itself; sudo is only needed once
# to add the user to the 'input' group so the daemon can read keyboard
# events globally):
#
#   1. Verifies Python ≥ 3.10 and the system tools we depend on
#      (wl-copy, ydotool optional, notify-send optional).
#   2. Installs the spitch-daemon and spitch-config launcher scripts
#      into ~/.local/bin (creates the dir if needed) — they point
#      PYTHONPATH at this repo's src/, so no compilation is required.
#   3. Prints next-step instructions: configure Doubao credentials and
#      add the user to the 'input' group for /dev/input read access.
#
# This script does NOT install a systemd user unit — once the daemon
# has been verified to work interactively, see docs/INSTALL.md for the
# optional service-style autostart.
set -euo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PYTHON="${PYTHON:-python3}"

err()  { echo "spitch-install: error: $*" >&2; exit 1; }
info() { echo "spitch-install: $*"; }

# 1. preflight
command -v "$PYTHON" >/dev/null 2>&1 || err "python3 not found"
"$PYTHON" - <<'PY' || err "python3 ≥ 3.10 required"
import sys
sys.exit(0 if sys.version_info >= (3, 10) else 1)
PY

missing=()
# A clipboard helper is required, but Wayland and X11 use different
# tools. Any one of wl-copy / xclip / xsel covers us; only complain
# when none of them is present.
if ! command -v wl-copy >/dev/null 2>&1 \
   && ! command -v xclip   >/dev/null 2>&1 \
   && ! command -v xsel    >/dev/null 2>&1; then
    missing+=("a clipboard helper (wl-clipboard for Wayland, or xclip/xsel for X11)")
fi
"$PYTHON" -c "import evdev" 2>/dev/null || missing+=("python3-evdev")
if [ "${#missing[@]}" -gt 0 ]; then
    info "missing system packages:"
    for m in "${missing[@]}"; do info "  - $m"; done
    info "install with (Wayland):  sudo apt-get install -y python3-evdev wl-clipboard"
    info "or (X11):                sudo apt-get install -y python3-evdev xclip"
    info "(then re-run this script)"
fi

BIN_DIR="${HOME}/.local/bin"
mkdir -p "$BIN_DIR"

# 2. launcher scripts
# Log under XDG_STATE_HOME (default ~/.local/state) so the path is
# user-private — writing to a fixed /tmp filename invites a symlink
# race where another process can pre-create /tmp/spitch.log → ~/some
# important file and have us append to it.
cat > "$BIN_DIR/spitch-daemon" <<EOF
#!/usr/bin/env bash
# generated by spitch install.sh
LOG_DIR="\${XDG_STATE_HOME:-\$HOME/.local/state}/spitch"
mkdir -p "\$LOG_DIR" && chmod 700 "\$LOG_DIR"
LOG_FILE="\$LOG_DIR/daemon.log"
exec >> "\$LOG_FILE" 2>&1
echo "==== daemon spawn \$(date '+%H:%M:%S') ===="
export PYTHONPATH="$REPO/src\${PYTHONPATH:+:\$PYTHONPATH}"
export PYTHONUNBUFFERED=1
exec "$PYTHON" -m spitch "\$@"
EOF
chmod +x "$BIN_DIR/spitch-daemon"

cat > "$BIN_DIR/spitch-config" <<EOF
#!/usr/bin/env bash
# generated by spitch install.sh
export PYTHONPATH="$REPO/src\${PYTHONPATH:+:\$PYTHONPATH}"
exec "$PYTHON" -m spitch.ui.config_dialog "\$@"
EOF
chmod +x "$BIN_DIR/spitch-config"

cat > "$BIN_DIR/spitch-cli" <<EOF
#!/usr/bin/env bash
# generated by spitch install.sh — talks to running daemon over Unix socket
export PYTHONPATH="$REPO/src\${PYTHONPATH:+:\$PYTHONPATH}"
exec "$PYTHON" -m spitch.cli "\$@"
EOF
chmod +x "$BIN_DIR/spitch-cli"

cat > "$BIN_DIR/spitch-console" <<EOF
#!/usr/bin/env bash
# generated by spitch install.sh — three-tab GTK console
export PYTHONPATH="$REPO/src\${PYTHONPATH:+:\$PYTHONPATH}"
exec "$PYTHON" -m spitch.ui.console "\$@"
EOF
chmod +x "$BIN_DIR/spitch-console"

info "installed $BIN_DIR/{spitch-daemon, spitch-config, spitch-cli, spitch-console}"

# 2.5. desktop entry + icon — so Spitch shows up in the application
# menu / activities overview, with an icon, opening the console
# directly to the settings tab. We install per-user (no sudo); the
# .desktop file references Icon=spitch which resolves through
# hicolor → ~/.local/share/icons/hicolor/scalable/apps/spitch.svg.
ICON_DIR="${HOME}/.local/share/icons/hicolor/scalable/apps"
DESKTOP_DIR="${HOME}/.local/share/applications"
mkdir -p "$ICON_DIR" "$DESKTOP_DIR"

ICON_SRC="$REPO/data/icons/spitch.svg"
if [ -f "$ICON_SRC" ]; then
    cp "$ICON_SRC" "$ICON_DIR/spitch.svg"
else
    # Fallback to the bundled tray icon — same artwork.
    cp "$REPO/src/spitch/tray/icons/spitch-idle.svg" "$ICON_DIR/spitch.svg"
fi

# Render the .desktop template — substitute the absolute path of the
# launcher we just generated. Avoids relying on $PATH at app-menu
# launch time (some DEs spawn .desktop entries with a minimal env).
DESKTOP_IN="$REPO/data/spitch.desktop.in"
if [ -f "$DESKTOP_IN" ]; then
    sed "s|@BIN_DIR@|$BIN_DIR|g" "$DESKTOP_IN" > "$DESKTOP_DIR/spitch.desktop"
    chmod +x "$DESKTOP_DIR/spitch.desktop"  # GNOME wants executable
fi

# Best-effort cache refresh so GNOME / KDE / Cinnamon pick up the
# new icon + desktop file without a logout. Both commands are no-ops
# on most modern stacks (file-watching does the work) — failure is
# harmless.
if command -v gtk-update-icon-cache >/dev/null 2>&1; then
    gtk-update-icon-cache -f -t "${HOME}/.local/share/icons/hicolor" 2>/dev/null || true
fi
if command -v update-desktop-database >/dev/null 2>&1; then
    update-desktop-database -q "$DESKTOP_DIR" 2>/dev/null || true
fi

info "installed application launcher (icon + .desktop) — open"
info "  Activities / 应用程序 → search 'Spitch' or '语音输入'"

case ":$PATH:" in
    *":$BIN_DIR:"*) ;;
    *) info "warning: $BIN_DIR is not on \$PATH — add it to ~/.bashrc:"
       info "  echo 'export PATH=\"\$HOME/.local/bin:\$PATH\"' >> ~/.bashrc" ;;
esac

# 3. next steps
cat <<EONOTE

spitch installed. Next steps:

  1. Configure Doubao credentials:

       spitch-config

     A small GTK dialog (or CLI fallback) opens. Paste your Volcano
     Engine BigASR APP ID into "X-Api-App-Key" and the Access Token
     into "X-Api-Access-Key", then click "Test connection". Only on
     success is the config saved.

  2. Grant /dev/input read access — needed so the daemon can detect
     the global hotkey from any focused app:

       sudo usermod -aG input \$USER

     Log out and back in for the new group to take effect (or use
     'sg input -c "spitch-daemon"' to test in a one-off shell first).

  3. Run the daemon:

       spitch-daemon &

     A "Spitch ready" notification appears. Hold the configured talk
     key (default Ctrl+Alt — both held simultaneously) to record;
     release to commit the punctuated final transcript into the
     focused app via clipboard + synthetic Ctrl+V.

  4. (optional) auto-start the daemon at login by enabling the
     systemd user unit shown in docs/INSTALL.md.

EONOTE
