#!/usr/bin/env bash
# User-level installer for the Spitch voice-input daemon (v0.2).
#
# What it does (no sudo for the package itself; sudo is only needed once
# to add the user to the 'input' group so the daemon can read keyboard
# events globally):
#
#   1. Verifies Python ≥ 3.10 and the system tools we depend on
#      (wl-copy, ydotool optional, notify-send optional).
#   2. Installs the spitch-daemon and spitch-config launcher scripts
#      into ~/.local/bin (creates the dir if needed) — they point
#      PYTHONPATH at this repo's src/, so no compilation is required.
#   3. Prints next-step instructions: configure Doubao credentials and
#      add the user to the 'input' group for /dev/input read access.
#
# This script does NOT install a systemd user unit — once the daemon
# has been verified to work interactively, see docs/INSTALL.md for the
# optional service-style autostart.
set -euo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PYTHON="${PYTHON:-python3}"

err()  { echo "spitch-install: error: $*" >&2; exit 1; }
info() { echo "spitch-install: $*"; }

# 1. preflight
command -v "$PYTHON" >/dev/null 2>&1 || err "python3 not found"
"$PYTHON" - <<'PY' || err "python3 ≥ 3.10 required"
import sys
sys.exit(0 if sys.version_info >= (3, 10) else 1)
PY

missing=()
# A clipboard helper is required, but Wayland and X11 use different
# tools. Any one of wl-copy / xclip / xsel covers us; only complain
# when none of them is present.
if ! command -v wl-copy >/dev/null 2>&1 \
   && ! command -v xclip   >/dev/null 2>&1 \
   && ! command -v xsel    >/dev/null 2>&1; then
    missing+=("a clipboard helper (wl-clipboard for Wayland, or xclip/xsel for X11)")
fi
"$PYTHON" -c "import evdev" 2>/dev/null || missing+=("python3-evdev")
if [ "${#missing[@]}" -gt 0 ]; then
    info "missing system packages:"
    for m in "${missing[@]}"; do info "  - $m"; done
    info "install with (Wayland):  sudo apt-get install -y python3-evdev wl-clipboard"
    info "or (X11):                sudo apt-get install -y python3-evdev xclip"
    info "(then re-run this script)"
fi

BIN_DIR="${HOME}/.local/bin"
mkdir -p "$BIN_DIR"

# 2. launcher scripts
# Log under XDG_STATE_HOME (default ~/.local/state) so the path is
# user-private — writing to a fixed /tmp filename invites a symlink
# race where another process can pre-create /tmp/spitch.log → ~/some
# important file and have us append to it.
cat > "$BIN_DIR/spitch-daemon" <<EOF
#!/usr/bin/env bash
# generated by spitch install.sh
LOG_DIR="\${XDG_STATE_HOME:-\$HOME/.local/state}/spitch"
mkdir -p "\$LOG_DIR" && chmod 700 "\$LOG_DIR"
LOG_FILE="\$LOG_DIR/daemon.log"
exec >> "\$LOG_FILE" 2>&1
echo "==== daemon spawn \$(date '+%H:%M:%S') ===="
export PYTHONPATH="$REPO/src\${PYTHONPATH:+:\$PYTHONPATH}"
export PYTHONUNBUFFERED=1
exec "$PYTHON" -m spitch "\$@"
EOF
chmod +x "$BIN_DIR/spitch-daemon"

cat > "$BIN_DIR/spitch-config" <<EOF
#!/usr/bin/env bash
# generated by spitch install.sh
export PYTHONPATH="$REPO/src\${PYTHONPATH:+:\$PYTHONPATH}"
exec "$PYTHON" -m spitch.ui.config_dialog "\$@"
EOF
chmod +x "$BIN_DIR/spitch-config"

cat > "$BIN_DIR/spitch-cli" <<EOF
#!/usr/bin/env bash
# generated by spitch install.sh — talks to running daemon over Unix socket
export PYTHONPATH="$REPO/src\${PYTHONPATH:+:\$PYTHONPATH}"
exec "$PYTHON" -m spitch.cli "\$@"
EOF
chmod +x "$BIN_DIR/spitch-cli"

cat > "$BIN_DIR/spitch-console" <<EOF
#!/usr/bin/env bash
# generated by spitch install.sh — three-tab GTK console
export PYTHONPATH="$REPO/src\${PYTHONPATH:+:\$PYTHONPATH}"
exec "$PYTHON" -m spitch.ui.console "\$@"
EOF
chmod +x "$BIN_DIR/spitch-console"

info "installed $BIN_DIR/{spitch-daemon, spitch-config, spitch-cli, spitch-console}"

case ":$PATH:" in
    *":$BIN_DIR:"*) ;;
    *) info "warning: $BIN_DIR is not on \$PATH — add it to ~/.bashrc:"
       info "  echo 'export PATH=\"\$HOME/.local/bin:\$PATH\"' >> ~/.bashrc" ;;
esac

# 3. next steps
cat <<EONOTE

spitch installed. Next steps:

  1. Configure Doubao credentials:

       spitch-config

     A small GTK dialog (or CLI fallback) opens. Paste your Volcano
     Engine BigASR APP ID into "X-Api-App-Key" and the Access Token
     into "X-Api-Access-Key", then click "Test connection". Only on
     success is the config saved.

  2. Grant /dev/input read access — needed so the daemon can detect
     the global hotkey from any focused app:

       sudo usermod -aG input \$USER

     Log out and back in for the new group to take effect (or use
     'sg input -c "spitch-daemon"' to test in a one-off shell first).

  3. Run the daemon:

       spitch-daemon &

     A "Spitch ready" notification appears. Hold the configured talk
     key (default Ctrl+Alt — both held simultaneously) to record;
     release to commit the punctuated final transcript into the
     focused app via clipboard + synthetic Ctrl+V.

  4. (optional) auto-start the daemon at login by enabling the
     systemd user unit shown in docs/INSTALL.md.

EONOTE
